services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es01
    tty: true # Equivalent to -i flag
    stdin_open: true # Equivalent to -t flag
    mem_limit: 1GB # Equivalent to -m 1GB flag
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
      ELASTICSEARCH_URL: http://es01:9200
    networks:
      - elastic
    depends_on:
      - es01

volumes:
  elasticsearch-data:
    driver: local
networks:
  elastic:
    driver: bridge
